Updated src with Bryan and My assets
blst15ki/CS-6334-Project pull request #11
Opened 2024-03-27 17:03 UTC by Milind21

2024-03-29 02:58 UTC, blst15ki requested changes
- Character speed too fast, please adjust character speed to 10
- Need to add mesh colliders for the fences so the player can't pass through them
- Adjust height offset's y value under the character game object to 1

2024-03-29 18:39 UTC, Milind21 commented
Added requested changes.

2024-03-30 03:34 UTC, blst15ki commented
Character speed feels a bit slow and the character height is lower than expected, but I will make these changes myself later.

2024-03-30 03:34 UTC, blst15ki approved these changes

2024-03-30 03:35 UTC, merged