Added Start Scene
blst15ki/CS-6334-Project pull request #32
Opened 2024-04-22 23:19 UTC by Milind21

-Added start menu as a new scene.
-Triggers customize menu which can be used to enter the scene.

2024-04-22 23:20 UTC, Milind21 commented
@blst15ki can you take a look at the wait logic? I have added a wait time which just works for the first time. Apart from that the menu works as expected

2024-04-23 03:27 UTC, blst15ki commented on Assets/Scripts/MainMenu.cs
> +        if (customizeMenuScript.wait)
When running in the start scene, it throws a NullReferenceException since customizeMenuScript in the Main Menu script is not set in the Start scene.

2024-04-23 03:30 UTC, blst15ki commented on Assets/Scenes/Start.unity
Could you add Garden Sim as the title?

2024-04-23 03:33 UTC, blst15ki commented on Assets/Scripts/CustomizeMenu.cs
> +        // imagea1.color = Color.yellow; // By default selection on avatar 1
Should be kept (highlight first option to avoid confusing player)

2024-04-23 03:34 UTC, blst15ki commented
Sorry I was clicking the wrong button, meant to post altogether as a single review instead of multiple single comments.

2024-04-23 03:47 UTC, blst15ki requested changes
The real reason why both menus were working at the same time is because you don't have only one menu script running at a time. For example, at the start, both scripts are active so when you hit X to cycle the options, the CycleButton method is called for both scripts. In this case, I don't think you need to set a wait boolean variable.

2024-04-23 03:47 UTC, blst15ki commented on Assets/Scripts/MainMenu.cs
> +        // image0.color = Color.yellow;
Should also be kept to avoid confusing player (let them know what button is first)

2024-04-23 04:02 UTC, Milind21 commented
- disable and enable the scripts too 
- remove the bools

2024-04-24 00:08 UTC, blst15ki requested changes
Start scene looks good in the editor now.
- Could you add the source of the background to the source file?
- The start screen needs to be linked to a camera (does not show up on Android)
- Can you resize the elements to fit closer together? For the main menu, the title is barely visible and the exit button is at the center. For the customize menu, the avatar options go off the screen.

2024-04-24 00:20 UTC, Milind21 commented
1) Is this related to screen overlay and screen camera? 
2) If so will the normal main camera work or do I have to setup the basic character from assignment 1?

2024-04-24 00:53 UTC, blst15ki commented
> 1. Is this related to screen overlay and screen camera?
> 2. If so will the normal main camera work or do I have to setup the basic character from assignment 1?

1. Yes, it is related. The canvas needs to be on screen camera.
2. Yes, the current main camera will work.

2024-04-24 19:31 UTC, blst15ki approved these changes

2024-04-24 19:31 UTC, merged